#version: '3.8'
services:
  app:
    build: .
    restart: no
    ports:
      - "8687:8687"
    depends_on:
#      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/week1_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/week1_db?reconnect=true&connectTimeout=30000
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
      LOGGING_LEVEL_ROOT: DEBUG
#      LOGGING_LEVEL_ROOT: ERROR
    networks:
      - app_network
    command: ["java", "-jar", "build/libs/kafka-web-1.0.0.jar"]

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: week1_db
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "week1_db"]
      interval: 10s
      retries: 5
      start_period: 30s

#  kafka:
#    image: confluentinc/cp-kafka:7.2.1
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_CREATE_TOPICS: "notifications:1:1"
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#    depends_on:
#      - zookeeper
#    networks:
#      - app_network
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - "8080:8080"
#    environment:
#      KAFKA_CLUSTERS_0_NAME: my-cluster
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
#    depends_on:
#      - kafka
#    networks:
#      - app_network
#    dns:
#      - 8.8.8.8
#      - 8.8.4.4
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    networks:
#      - app_network

networks:
  app_network:
    driver: bridge