spring:
  application:
    name: kafka-web
  kafka:
#    bootstrap-servers: localhost:9092

    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    consumer:
      group-id: notifications-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      key-deserializer: org.apache.kafka.connect.json.JsonDeserializer
#      value-deserializer: org.apache.kafka.connect.json.JsonDeserializer
  r2dbc:
#        url: r2dbc:postgresql://localhost:5432/week1_db
#        username: postgres
#        password: password
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

  datasource:
#    url: jdbc:postgresql://localhost:5432/week1_db
#    username: postgres
#    password: password
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:

    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

#    url: jdbc:postgresql://localhost:5432/week1_db
#    user: postgres
#    password: password

    locations: classpath:db/migration
